language: node_js
node_js:
  - "0.8"
before_install:
  - echo "127.0.0.1 localhost-legacy" | sudo tee -a /etc/hosts
  - sudo apt-get install octave imagemagick tesseract-ocr tesseract-ocr-deu
script: make setup && make lint && make test
services: mongodb
