language: node_js
node_js:
  - "0.10"
before_install:
  - echo "127.0.0.1 localhost-legacy" | sudo tee -a /etc/hosts
  - sudo apt-get update
  - sudo apt-get install poppler-utils
script: make travis
services: mongodb
